#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef MOBWITHADSDKFRAMEWORK_SWIFT_H
#define MOBWITHADSDKFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MobWithADSDKFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
IB_DESIGNABLE
SWIFT_CLASS("_TtC21MobWithADSDKFramework13DHPaddedLabel")
@interface DHPaddedLabel : UILabel
@property (nonatomic) IBInspectable CGFloat topInset;
@property (nonatomic) IBInspectable CGFloat bottomInset;
@property (nonatomic) IBInspectable CGFloat leftInset;
@property (nonatomic) IBInspectable CGFloat rightInset;
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol MobWithADViewDelegate;
@class NSString;
SWIFT_CLASS("_TtC21MobWithADSDKFramework10MMAdLoader")
@interface MMAdLoader : NSObject
@property (nonatomic, weak) id <MobWithADViewDelegate> _Nullable adDelegate;
/// AD Loader
/// \param bannerUnitId 발급받은 광고 지면 ID
///
- (nonnull instancetype)initWithBannerUnitId:(NSString * _Nonnull)bannerUnitId OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface MMAdLoader (SWIFT_EXTENSION(MobWithADSDKFramework))
/// 광고 InfoMark 클릭 이벤트 처리
- (void)openAdInfoUrl;
/// 광고 클릭 이벤트 처리
- (void)openAdUrl;
/// 광고 노출시 호출.
- (void)sendImpression;
@end

enum MMAdType : NSInteger;
@class UIView;
SWIFT_CLASS("_TtC21MobWithADSDKFramework15MMAdRequestInfo")
@interface MMAdRequestInfo : NSObject
@property (nonatomic, readonly) enum MMAdType adType;
@property (nonatomic, readonly, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, readonly) BOOL fillMode;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, readonly, strong) UIView * _Nullable containerView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, MMAdType, open) {
  MMAdTypeBanner = 0,
  MMAdTypeInterstitial = 1,
  MMAdTypeNative = 2,
  MMAdTypeReward = 3,
  MMAdTypePopup = 4,
  MMAdTypeBizboard = 5,
};

typedef SWIFT_ENUM(NSInteger, MMBannerType, open) {
  MMBannerTypeBANNER_320x50 = 0,
  MMBannerTypeBANNER_320x100 = 1,
  MMBannerTypeBANNER_300x250 = 2,
};

@class UIImageView;
@class UIButton;
SWIFT_CLASS("_TtC21MobWithADSDKFramework14MMNativeAdView")
@interface MMNativeAdView : UIView
@property (nonatomic, weak) id <MobWithADViewDelegate> _Nullable adDelegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Native AD View
/// Tag값의 설정이 필요한 View의 경우 Tag값을 설정하지 않았거나, 0인 경우 SDK 내부에서 임의의 Tag값을 설정한다. (미디에션기능을 지원하는 몇몇 SDK의 설정을 위함)
/// \param bannerUnitId 발급받은 광고 지면 ID
///
/// \param adContainerView 광고 View를 표시할 View.  AppLovin을 미디에이션하기 위해서는 MANativeAdView를 만들어서 내려줘야 한다.
///
/// \param nativeAdRootView 커스텀된 메인 광고 View.  광고 Image, Title 라벨등 하위 뷰를 포함하는 상위 View
///
/// \param adImageView 광고 Image를 표시할 ImageView. Tag값 설정 필요
///
/// \param logoImageView 광고주  로고를 표시할 ImageView. Tag값 설정 필요
///
/// \param titleLabel 광고 Title을 표시할 Label. Tag값 설정 필요
///
/// \param descriptionLabel 광고에 대한 설명이 표시될 Label. Tag값 설정 필요
///
/// \param gotoSiteButton 광고 사이트 이동을 위한 Button. Tag값 설정 필요
///
/// \param infoLogoImageView 광고 Info Logo를 표시할 ImageView. Tag값 설정 필요
///
- (nonnull instancetype)initWithBannerUnitId:(NSString * _Nonnull)bannerUnitId adContainerView:(UIView * _Nullable)adContainerView nativeAdRootView:(UIView * _Nullable)nativeAdRootView adImageView:(UIImageView * _Nullable)adImageView logoImageView:(UIImageView * _Nullable)logoImageView titleLabel:(UILabel * _Nullable)titleLabel descriptionLabel:(UILabel * _Nullable)descriptionLabel gotoSiteButton:(UIButton * _Nullable)gotoSiteButton infoLogoImageView:(UIImageView * _Nullable)infoLogoImageView OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
@end

@interface MMNativeAdView (SWIFT_EXTENSION(MobWithADSDKFramework))
/// 제공하는 광고 클릭 영역이 아닌 다른 방법을 통해 광고 터치 동작을 수행하고자 하는 경우 광고 영역에 Touch 이벤트를 전달하기 위한 함수
- (void)performAdClicked;
@end

@protocol MWAdapterBase;
SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework17MWAdapterDelegate_")
@protocol MWAdapterDelegate
@optional
/// 광고를 수신한 경우 전달됨
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 광고 수신 실패시 전달
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
/// 광고를 클릭한 경우 전달됨
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 광고가 화면에 표시된 경우 전달됨.
- (void)mwAdapterAdDidOpendWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 광고오픈 실패시 전달됨.
- (void)mwAdapterAdDidOpenFailedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
/// 광고창을 닫은 경우 호출된다
- (void)mwAdapterAdClosedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 리워드 광고에서 리워드 제공 조건을 만족한 경우 호출된다.
- (void)mwAdapterAdCanRewardWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 앱 오픈 광고에서 ‘오늘 그만보기’ 버튼을 누른 경우
- (void)mwAdapterPopUpAdHideTodayWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

@interface MMNativeAdView (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework9MMPopUpAd")
@interface MMPopUpAd : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class NativeAdViewItem;
SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework13MWAdapterBase_")
@protocol MWAdapterBase
- (void)setDelegateWithDelegate:(id <MWAdapterDelegate> _Nullable)delegate;
- (void)setRootViewControllerWithRootViewController:(UIViewController * _Nullable)rootViewController;
- (void)setNativeAdViewItemWithNativeAdViewItem:(NativeAdViewItem * _Nullable)nativeAdViewItem;
- (BOOL)loadAdWithAdRequestInfo:(MMAdRequestInfo * _Nonnull)adRequestInfo SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)getAdViewWithType:(enum MMAdType)type SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showAdWithType:(enum MMAdType)type SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAdLoadedWithType:(enum MMAdType)type SWIFT_WARN_UNUSED_RESULT;
- (void)clearAdViews;
- (void)clearCustomViewInNativeAd;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework17MWAdapterRegister")
@interface MWAdapterRegister : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework25MWAdapterRegisterProtocol_")
@protocol MWAdapterRegisterProtocol
+ (id <MWAdapterBase> _Nonnull)initAdapterWithConfig:(NSDictionary<NSString *, id> * _Nullable)config SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework25MWAdapterSDKInitializable_")
@protocol MWAdapterSDKInitializable
/// config에는 기본값으로 [“AppKey” : “해당 SDK 초기화에 필요한 앱키”] 형태로 값을 할당해야 함.
/// 여기에서 AppKey는 각 SDK 마다 다른 이름으로 불리며, 대체로 해당 SDK 자체를 초기화 할 때 요구하는 값이 내려감
/// 추가로, Admob 같이 앱의 info.plist에 값을 지정하는 경우 config가 nil값을 내려줌
+ (void)initializeSDKWithConfig:(NSDictionary<NSString *, id> * _Nullable)config;
+ (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, MWAdapterType, open) {
  MWAdapterTypeAdmob = 0,
  MWAdapterTypePangle = 1,
  MWAdapterTypeInMobi = 2,
  MWAdapterTypeKakao = 3,
  MWAdapterTypeLevelPlay = 4,
  MWAdapterTypeDtExchange = 5,
  MWAdapterTypeAdop = 6,
  MWAdapterTypeCauly = 7,
};

/// MobMixerSDK 기본 관리 클래스
SWIFT_CLASS("_TtC21MobWithADSDKFramework12MobWithADSDK")
@interface MobWithADSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MobWithADSDK * _Nonnull standard;)
+ (MobWithADSDK * _Nonnull)standard SWIFT_WARN_UNUSED_RESULT;
/// App Store에 등록된 앱의 ID.  Cauly 미디에이션 사용시 필요한 값이며, 출시전 앱인 경우 0으로 지정할 수 있으나, 출시 후에는 반드시 앱 ID를 지정해야 한다.
@property (nonatomic, copy) NSString * _Nonnull appId;
/// SDK 버전 정보를 반환한다
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// App Store Url을 설정한다.  일부 DSP에서 앱스토어 URL이 필요할 수 있습니다.   appId를 설정하면 자동으로 생성됩니다.
@property (nonatomic, copy) NSString * _Nonnull appStoreUrl;
/// SDK 정보를 초기화 한다.
- (void)initSDK SWIFT_METHOD_FAMILY(none);
- (void)enableLog:(BOOL)enable;
- (void)setLevelPlaySDKAppKey:(NSString * _Nonnull)appKey;
- (void)setPangleAppIdWithAppId:(NSString * _Nonnull)appId;
- (void)setDTExchangeAppIDWithAppId:(NSString * _Nonnull)appId;
- (void)setInMobiAccountIdWithAccountId:(NSString * _Nonnull)accountId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework21MobWithADViewDelegate_")
@protocol MobWithADViewDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithAdViewClickedAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithAdViewDidReceivedAd;
/// 광고 수신 실패시 전달
- (void)mobWithAdViewDidFailToReceiveAd;
@end

@class UIWindow;
SWIFT_CLASS("_TtC21MobWithADSDKFramework13MobWithAdView")
@interface MobWithAdView : UIView
@property (nonatomic, weak) id <MobWithADViewDelegate> _Nullable adDelegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)init:(CGRect)frame type:(enum MMBannerType)type bannerUnitId:(NSString * _Nonnull)bannerUnitId OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
- (void)removeFromSuperview;
- (void)willMoveToWindow:(UIWindow * _Nullable)newWindow;
- (void)clearAdLoader;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface MobWithAdView (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

@class MobWithInterstitailAd;
SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework28MobWithIntersitialAdDelegate_")
@protocol MobWithIntersitialAdDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithIntersitialAdClicked:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithIntersitialAdDidReceived:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 광고 수신 실패시 전달
- (void)mobWithIntersitialAdDidFailToReceive:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 전면광고가 화면에 표시된 경우 전달됨.  전면 광고의 경우에만 전달 받을 수 있다.
- (void)mobWithIntersitialAdDidOpend:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 전면광고오픈 실패시 전달됨.
- (void)mobWithIntersitialAdDidOpenFailed:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 전면광고 창이 닫힌 경우 호출된다.
- (void)mobWithIntersitialAdDidClosed:(MobWithInterstitailAd * _Nullable)interstitialAd;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework21MobWithInterstitailAd")
@interface MobWithInterstitailAd : NSObject
@property (nonatomic, weak) id <MobWithIntersitialAdDelegate> _Nullable adDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
@end

@interface MobWithInterstitailAd (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpendWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpenFailedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClosedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

@protocol MobWithNativeAdLoaderDelegate;
@class NSBundle;
@class NSIndexPath;
SWIFT_CLASS("_TtC21MobWithADSDKFramework21MobWithNativeAdLoader")
@interface MobWithNativeAdLoader : NSObject
@property (nonatomic, strong) id <MobWithNativeAdLoaderDelegate> _Nullable nativeAdLoaderDelegate;
- (nonnull instancetype)initWithUnitIds:(NSArray<NSString *> * _Nonnull)unitIds nibName:(NSString * _Nonnull)nibName bundle:(NSBundle * _Nullable)bundle OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isLoadedAdAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isFailLoadAdAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)loadAdAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)retryLoadAdAt:(NSIndexPath * _Nonnull)indexPath;
- (void)destoryAds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework29MobWithNativeAdLoaderDelegate_")
@protocol MobWithNativeAdLoaderDelegate
@optional
- (void)mobWithNativeAdViewClickedAd;
- (void)mobWithNativeAdViewDidReceivedAdAt:(NSIndexPath * _Nullable)index;
- (void)mobWithNativeAdViewDidFailToReceiveAdAt:(NSIndexPath * _Nullable)index;
@end

@interface MobWithNativeAdLoader (SWIFT_EXTENSION(MobWithADSDKFramework)) <MobWithNativeAdLoaderDelegate>
- (void)mobWithNativeAdViewClickedAd;
- (void)mobWithNativeAdViewDidReceivedAdAt:(NSIndexPath * _Nullable)index;
- (void)mobWithNativeAdViewDidFailToReceiveAdAt:(NSIndexPath * _Nullable)index;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework22MobWithPopupAdDelegate_")
@protocol MobWithPopupAdDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithPopUpAdClicked:(MMPopUpAd * _Nullable)popAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithPopUpAdDidReceived:(MMPopUpAd * _Nullable)popAd;
/// 광고 수신 실패시 전달
- (void)mobWithPopUpAdDidFailToReceive:(MMPopUpAd * _Nullable)popAd;
/// 광고창을 닫은 경우 호출된다
- (void)mobWithRewardAdClosed:(MMPopUpAd * _Nullable)popAd;
/// 오늘 그만보기 버튼을 누른 경우
- (void)mobWithPopUpAdHideToday:(MMPopUpAd * _Nullable)popAd;
/// 광고를 화면에 표시하는데 실패한 경우
- (void)mobWithPopUpAdDidOpenFailed:(MMPopUpAd * _Nullable)popAd;
@end

@protocol MobWithRewardAdDelegate;
SWIFT_CLASS("_TtC21MobWithADSDKFramework15MobWithRewardAd")
@interface MobWithRewardAd : NSObject
@property (nonatomic, weak) id <MobWithRewardAdDelegate> _Nullable adDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
@end

@interface MobWithRewardAd (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpendWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpenFailedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClosedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdCanRewardWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework23MobWithRewardAdDelegate_")
@protocol MobWithRewardAdDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithRewardAdClicked:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithRewardAdDidReceived:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고 수신 실패시 전달
- (void)mobWithRewardAdDidFailToReceive:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고가 화면에 표시된 경우 전달됨.
- (void)mobWithRewardAdDidOpend:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고오픈 실패시 전달됨.
- (void)mobWithRewardAdDidOpenFailed:(MobWithRewardAd * _Nullable)rewardAd;
/// 리워드 제공 조건을 만족한 경우 호출된다.
- (void)mobWithRewardAdCanReward:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고창을 닫은 경우 호출된다
- (void)mobWithRewardAdClosed:(MobWithRewardAd * _Nullable)rewardAd;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework16NativeAdViewItem")
@interface NativeAdViewItem : NSObject
@property (nonatomic, strong) UIView * _Nullable nativeAdRootView;
@property (nonatomic, strong) UIView * _Nullable containerView;
@property (nonatomic, strong) UIImageView * _Nullable adImageView;
@property (nonatomic, strong) UIImageView * _Nullable adLogoImageView;
@property (nonatomic, strong) UILabel * _Nullable adTitleLabel;
@property (nonatomic, strong) UILabel * _Nullable adPriceLabel;
@property (nonatomic, strong) UIButton * _Nullable goToSiteButton;
@property (nonatomic, strong) UIImageView * _Nullable infoLogoImageView;
@property (nonatomic, strong) UIView * _Nullable mediaView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef MOBWITHADSDKFRAMEWORK_SWIFT_H
#define MOBWITHADSDKFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MobWithADSDKFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
IB_DESIGNABLE
SWIFT_CLASS("_TtC21MobWithADSDKFramework13DHPaddedLabel")
@interface DHPaddedLabel : UILabel
@property (nonatomic) IBInspectable CGFloat topInset;
@property (nonatomic) IBInspectable CGFloat bottomInset;
@property (nonatomic) IBInspectable CGFloat leftInset;
@property (nonatomic) IBInspectable CGFloat rightInset;
- (void)drawTextInRect:(CGRect)rect;
@property (nonatomic, readonly) CGSize intrinsicContentSize;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol MobWithADViewDelegate;
@class NSString;
SWIFT_CLASS("_TtC21MobWithADSDKFramework10MMAdLoader")
@interface MMAdLoader : NSObject
@property (nonatomic, weak) id <MobWithADViewDelegate> _Nullable adDelegate;
/// AD Loader
/// \param bannerUnitId 발급받은 광고 지면 ID
///
- (nonnull instancetype)initWithBannerUnitId:(NSString * _Nonnull)bannerUnitId OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface MMAdLoader (SWIFT_EXTENSION(MobWithADSDKFramework))
/// 광고 InfoMark 클릭 이벤트 처리
- (void)openAdInfoUrl;
/// 광고 클릭 이벤트 처리
- (void)openAdUrl;
/// 광고 노출시 호출.
- (void)sendImpression;
@end

enum MMAdType : NSInteger;
@class UIView;
SWIFT_CLASS("_TtC21MobWithADSDKFramework15MMAdRequestInfo")
@interface MMAdRequestInfo : NSObject
@property (nonatomic, readonly) enum MMAdType adType;
@property (nonatomic, readonly, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, readonly) BOOL fillMode;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, readonly, strong) UIView * _Nullable containerView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, MMAdType, open) {
  MMAdTypeBanner = 0,
  MMAdTypeInterstitial = 1,
  MMAdTypeNative = 2,
  MMAdTypeReward = 3,
  MMAdTypePopup = 4,
  MMAdTypeBizboard = 5,
};

typedef SWIFT_ENUM(NSInteger, MMBannerType, open) {
  MMBannerTypeBANNER_320x50 = 0,
  MMBannerTypeBANNER_320x100 = 1,
  MMBannerTypeBANNER_300x250 = 2,
};

@class UIImageView;
@class UIButton;
SWIFT_CLASS("_TtC21MobWithADSDKFramework14MMNativeAdView")
@interface MMNativeAdView : UIView
@property (nonatomic, weak) id <MobWithADViewDelegate> _Nullable adDelegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
/// Native AD View
/// Tag값의 설정이 필요한 View의 경우 Tag값을 설정하지 않았거나, 0인 경우 SDK 내부에서 임의의 Tag값을 설정한다. (미디에션기능을 지원하는 몇몇 SDK의 설정을 위함)
/// \param bannerUnitId 발급받은 광고 지면 ID
///
/// \param adContainerView 광고 View를 표시할 View.  AppLovin을 미디에이션하기 위해서는 MANativeAdView를 만들어서 내려줘야 한다.
///
/// \param nativeAdRootView 커스텀된 메인 광고 View.  광고 Image, Title 라벨등 하위 뷰를 포함하는 상위 View
///
/// \param adImageView 광고 Image를 표시할 ImageView. Tag값 설정 필요
///
/// \param logoImageView 광고주  로고를 표시할 ImageView. Tag값 설정 필요
///
/// \param titleLabel 광고 Title을 표시할 Label. Tag값 설정 필요
///
/// \param descriptionLabel 광고에 대한 설명이 표시될 Label. Tag값 설정 필요
///
/// \param gotoSiteButton 광고 사이트 이동을 위한 Button. Tag값 설정 필요
///
/// \param infoLogoImageView 광고 Info Logo를 표시할 ImageView. Tag값 설정 필요
///
- (nonnull instancetype)initWithBannerUnitId:(NSString * _Nonnull)bannerUnitId adContainerView:(UIView * _Nullable)adContainerView nativeAdRootView:(UIView * _Nullable)nativeAdRootView adImageView:(UIImageView * _Nullable)adImageView logoImageView:(UIImageView * _Nullable)logoImageView titleLabel:(UILabel * _Nullable)titleLabel descriptionLabel:(UILabel * _Nullable)descriptionLabel gotoSiteButton:(UIButton * _Nullable)gotoSiteButton infoLogoImageView:(UIImageView * _Nullable)infoLogoImageView OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
@end

@interface MMNativeAdView (SWIFT_EXTENSION(MobWithADSDKFramework))
/// 제공하는 광고 클릭 영역이 아닌 다른 방법을 통해 광고 터치 동작을 수행하고자 하는 경우 광고 영역에 Touch 이벤트를 전달하기 위한 함수
- (void)performAdClicked;
@end

@protocol MWAdapterBase;
SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework17MWAdapterDelegate_")
@protocol MWAdapterDelegate
@optional
/// 광고를 수신한 경우 전달됨
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 광고 수신 실패시 전달
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
/// 광고를 클릭한 경우 전달됨
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 광고가 화면에 표시된 경우 전달됨.
- (void)mwAdapterAdDidOpendWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 광고오픈 실패시 전달됨.
- (void)mwAdapterAdDidOpenFailedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
/// 광고창을 닫은 경우 호출된다
- (void)mwAdapterAdClosedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 리워드 광고에서 리워드 제공 조건을 만족한 경우 호출된다.
- (void)mwAdapterAdCanRewardWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
/// 앱 오픈 광고에서 ‘오늘 그만보기’ 버튼을 누른 경우
- (void)mwAdapterPopUpAdHideTodayWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

@interface MMNativeAdView (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework9MMPopUpAd")
@interface MMPopUpAd : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIViewController;
@class NativeAdViewItem;
SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework13MWAdapterBase_")
@protocol MWAdapterBase
- (void)setDelegateWithDelegate:(id <MWAdapterDelegate> _Nullable)delegate;
- (void)setRootViewControllerWithRootViewController:(UIViewController * _Nullable)rootViewController;
- (void)setNativeAdViewItemWithNativeAdViewItem:(NativeAdViewItem * _Nullable)nativeAdViewItem;
- (BOOL)loadAdWithAdRequestInfo:(MMAdRequestInfo * _Nonnull)adRequestInfo SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)getAdViewWithType:(enum MMAdType)type SWIFT_WARN_UNUSED_RESULT;
- (BOOL)showAdWithType:(enum MMAdType)type SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAdLoadedWithType:(enum MMAdType)type SWIFT_WARN_UNUSED_RESULT;
- (void)clearAdViews;
- (void)clearCustomViewInNativeAd;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework17MWAdapterRegister")
@interface MWAdapterRegister : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework25MWAdapterRegisterProtocol_")
@protocol MWAdapterRegisterProtocol
+ (id <MWAdapterBase> _Nonnull)initAdapterWithConfig:(NSDictionary<NSString *, id> * _Nullable)config SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework25MWAdapterSDKInitializable_")
@protocol MWAdapterSDKInitializable
/// config에는 기본값으로 [“AppKey” : “해당 SDK 초기화에 필요한 앱키”] 형태로 값을 할당해야 함.
/// 여기에서 AppKey는 각 SDK 마다 다른 이름으로 불리며, 대체로 해당 SDK 자체를 초기화 할 때 요구하는 값이 내려감
/// 추가로, Admob 같이 앱의 info.plist에 값을 지정하는 경우 config가 nil값을 내려줌
+ (void)initializeSDKWithConfig:(NSDictionary<NSString *, id> * _Nullable)config;
+ (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, MWAdapterType, open) {
  MWAdapterTypeAdmob = 0,
  MWAdapterTypePangle = 1,
  MWAdapterTypeInMobi = 2,
  MWAdapterTypeKakao = 3,
  MWAdapterTypeLevelPlay = 4,
  MWAdapterTypeDtExchange = 5,
  MWAdapterTypeAdop = 6,
  MWAdapterTypeCauly = 7,
};

/// MobMixerSDK 기본 관리 클래스
SWIFT_CLASS("_TtC21MobWithADSDKFramework12MobWithADSDK")
@interface MobWithADSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) MobWithADSDK * _Nonnull standard;)
+ (MobWithADSDK * _Nonnull)standard SWIFT_WARN_UNUSED_RESULT;
/// App Store에 등록된 앱의 ID.  Cauly 미디에이션 사용시 필요한 값이며, 출시전 앱인 경우 0으로 지정할 수 있으나, 출시 후에는 반드시 앱 ID를 지정해야 한다.
@property (nonatomic, copy) NSString * _Nonnull appId;
/// SDK 버전 정보를 반환한다
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull sdkVersion;)
+ (NSString * _Nonnull)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// App Store Url을 설정한다.  일부 DSP에서 앱스토어 URL이 필요할 수 있습니다.   appId를 설정하면 자동으로 생성됩니다.
@property (nonatomic, copy) NSString * _Nonnull appStoreUrl;
/// SDK 정보를 초기화 한다.
- (void)initSDK SWIFT_METHOD_FAMILY(none);
- (void)enableLog:(BOOL)enable;
- (void)setLevelPlaySDKAppKey:(NSString * _Nonnull)appKey;
- (void)setPangleAppIdWithAppId:(NSString * _Nonnull)appId;
- (void)setDTExchangeAppIDWithAppId:(NSString * _Nonnull)appId;
- (void)setInMobiAccountIdWithAccountId:(NSString * _Nonnull)accountId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework21MobWithADViewDelegate_")
@protocol MobWithADViewDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithAdViewClickedAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithAdViewDidReceivedAd;
/// 광고 수신 실패시 전달
- (void)mobWithAdViewDidFailToReceiveAd;
@end

@class UIWindow;
SWIFT_CLASS("_TtC21MobWithADSDKFramework13MobWithAdView")
@interface MobWithAdView : UIView
@property (nonatomic, weak) id <MobWithADViewDelegate> _Nullable adDelegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)init:(CGRect)frame type:(enum MMBannerType)type bannerUnitId:(NSString * _Nonnull)bannerUnitId OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
- (void)removeFromSuperview;
- (void)willMoveToWindow:(UIWindow * _Nullable)newWindow;
- (void)clearAdLoader;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface MobWithAdView (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

@class MobWithInterstitailAd;
SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework28MobWithIntersitialAdDelegate_")
@protocol MobWithIntersitialAdDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithIntersitialAdClicked:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithIntersitialAdDidReceived:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 광고 수신 실패시 전달
- (void)mobWithIntersitialAdDidFailToReceive:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 전면광고가 화면에 표시된 경우 전달됨.  전면 광고의 경우에만 전달 받을 수 있다.
- (void)mobWithIntersitialAdDidOpend:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 전면광고오픈 실패시 전달됨.
- (void)mobWithIntersitialAdDidOpenFailed:(MobWithInterstitailAd * _Nullable)interstitialAd;
/// 전면광고 창이 닫힌 경우 호출된다.
- (void)mobWithIntersitialAdDidClosed:(MobWithInterstitailAd * _Nullable)interstitialAd;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework21MobWithInterstitailAd")
@interface MobWithInterstitailAd : NSObject
@property (nonatomic, weak) id <MobWithIntersitialAdDelegate> _Nullable adDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
@end

@interface MobWithInterstitailAd (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpendWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpenFailedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClosedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

@protocol MobWithNativeAdLoaderDelegate;
@class NSBundle;
@class NSIndexPath;
SWIFT_CLASS("_TtC21MobWithADSDKFramework21MobWithNativeAdLoader")
@interface MobWithNativeAdLoader : NSObject
@property (nonatomic, strong) id <MobWithNativeAdLoaderDelegate> _Nullable nativeAdLoaderDelegate;
- (nonnull instancetype)initWithUnitIds:(NSArray<NSString *> * _Nonnull)unitIds nibName:(NSString * _Nonnull)nibName bundle:(NSBundle * _Nullable)bundle OBJC_DESIGNATED_INITIALIZER;
- (BOOL)isLoadedAdAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isFailLoadAdAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)loadAdAt:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)retryLoadAdAt:(NSIndexPath * _Nonnull)indexPath;
- (void)destoryAds;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework29MobWithNativeAdLoaderDelegate_")
@protocol MobWithNativeAdLoaderDelegate
@optional
- (void)mobWithNativeAdViewClickedAd;
- (void)mobWithNativeAdViewDidReceivedAdAt:(NSIndexPath * _Nullable)index;
- (void)mobWithNativeAdViewDidFailToReceiveAdAt:(NSIndexPath * _Nullable)index;
@end

@interface MobWithNativeAdLoader (SWIFT_EXTENSION(MobWithADSDKFramework)) <MobWithNativeAdLoaderDelegate>
- (void)mobWithNativeAdViewClickedAd;
- (void)mobWithNativeAdViewDidReceivedAdAt:(NSIndexPath * _Nullable)index;
- (void)mobWithNativeAdViewDidFailToReceiveAdAt:(NSIndexPath * _Nullable)index;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework22MobWithPopupAdDelegate_")
@protocol MobWithPopupAdDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithPopUpAdClicked:(MMPopUpAd * _Nullable)popAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithPopUpAdDidReceived:(MMPopUpAd * _Nullable)popAd;
/// 광고 수신 실패시 전달
- (void)mobWithPopUpAdDidFailToReceive:(MMPopUpAd * _Nullable)popAd;
/// 광고창을 닫은 경우 호출된다
- (void)mobWithRewardAdClosed:(MMPopUpAd * _Nullable)popAd;
/// 오늘 그만보기 버튼을 누른 경우
- (void)mobWithPopUpAdHideToday:(MMPopUpAd * _Nullable)popAd;
/// 광고를 화면에 표시하는데 실패한 경우
- (void)mobWithPopUpAdDidOpenFailed:(MMPopUpAd * _Nullable)popAd;
@end

@protocol MobWithRewardAdDelegate;
SWIFT_CLASS("_TtC21MobWithADSDKFramework15MobWithRewardAd")
@interface MobWithRewardAd : NSObject
@property (nonatomic, weak) id <MobWithRewardAdDelegate> _Nullable adDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)loadAd;
@end

@interface MobWithRewardAd (SWIFT_EXTENSION(MobWithADSDKFramework)) <MWAdapterDelegate>
- (void)mwAdapterDidReceivedAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterDidFailToReceiveAdWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClickedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpendWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdDidOpenFailedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter error:(NSError * _Nullable)error;
- (void)mwAdapterAdClosedWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
- (void)mwAdapterAdCanRewardWithAdapter:(id <MWAdapterBase> _Nonnull)adapter;
@end

SWIFT_PROTOCOL("_TtP21MobWithADSDKFramework23MobWithRewardAdDelegate_")
@protocol MobWithRewardAdDelegate
@optional
/// 광고를 클릭한 경우 전달됨
- (void)mobWithRewardAdClicked:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고를 수신한 경우 전달됨
- (void)mobWithRewardAdDidReceived:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고 수신 실패시 전달
- (void)mobWithRewardAdDidFailToReceive:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고가 화면에 표시된 경우 전달됨.
- (void)mobWithRewardAdDidOpend:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고오픈 실패시 전달됨.
- (void)mobWithRewardAdDidOpenFailed:(MobWithRewardAd * _Nullable)rewardAd;
/// 리워드 제공 조건을 만족한 경우 호출된다.
- (void)mobWithRewardAdCanReward:(MobWithRewardAd * _Nullable)rewardAd;
/// 광고창을 닫은 경우 호출된다
- (void)mobWithRewardAdClosed:(MobWithRewardAd * _Nullable)rewardAd;
@end

SWIFT_CLASS("_TtC21MobWithADSDKFramework16NativeAdViewItem")
@interface NativeAdViewItem : NSObject
@property (nonatomic, strong) UIView * _Nullable nativeAdRootView;
@property (nonatomic, strong) UIView * _Nullable containerView;
@property (nonatomic, strong) UIImageView * _Nullable adImageView;
@property (nonatomic, strong) UIImageView * _Nullable adLogoImageView;
@property (nonatomic, strong) UILabel * _Nullable adTitleLabel;
@property (nonatomic, strong) UILabel * _Nullable adPriceLabel;
@property (nonatomic, strong) UIButton * _Nullable goToSiteButton;
@property (nonatomic, strong) UIImageView * _Nullable infoLogoImageView;
@property (nonatomic, strong) UIView * _Nullable mediaView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
