source 'https://cdn.cocoapods.org/'
source 'https://github.com/mobon/MobwithAdSpecs.git'


target 'Sample' do

  use_frameworks!

  pod 'MobWithAdSDK', '1.3.29'
  
  pod 'MobWithAdFitAdapter', '3.21.24.1.3.2'
  pod 'MobWithAdMobAdapter', '12.14.0.1.3.21'
  pod 'MobWithCaulyAdapter', '3.1.22.1.3.1'
  pod 'MobWithDTExchangeAdapter', '8.4.2.1.3.1'
  pod 'MobWithInMobiAdapter', '11.1.0.1.3.1'
  pod 'MobWithLevelPlayAdapter', '9.2.0.0.1.3.1'
  pod 'MobWithPangleAdapter', '7.8.0.4.1.3.1'
  pod 'MobWithAdPopcornAdapter', '3.3.2.1.3.26'

#  pod 'MobWithBidMadAdapter', '6.13.6.1.3.21'
#  pod 'BidmadAdmixerAdapter', '2.0.2.12.2'        #BidMad의 경우 무조건 하나 이상의 Adapter를 적용해야 초기화에 성공한다.
#  pod "OpenBiddingHelper", '6.13.2'
#  pod 'BidmadSDK/core', '= 6.13.6'
#  pod "BidmadGoogleAdManagerAdapter", "12.6.0.12.1"
#  pod "BidmadGoogleAdMobAdapter", "12.6.0.12.1"
  
end
